[tool.poetry]
name = "pyfinn"
version = "0.1.0"
description = "Fetch real estate listing from finn.no and make available as JSON"
authors = ["Nikolai R Kristiansen <nikolaik@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<4"

requests-html = "*"
flask = "*"
gunicorn = "*"
redis = "*"
fake-useragent = "*"
urllib3 = ">=1.24.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
black = "^22.3.0"
responses = "^0.20.0"
pytest-socket = "^0.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length=120

[tool.pytest.ini_options]
addopts = "--allow-hosts=localhost,127.0.0.1,::1"